### ISSUE TITLE
Add optional fallback default value for missing variables

### ISSUE THREAD

**Issue by a-alamoudi** [molinch/ConfigurationSubstitutor#11]
Hi,

First, thanks for making this very cool and valuable project. Here, I'd like to request a feature that allows the user to specify a fallback default value in case the environment variable is missing. Such a feature could help ease the deployment process, as some smart defaults can be passed within the same config file and get substituted in case their EVs are missing. This feature is inspired by the[`PlaceholderConfigurerSupport` from the Spring Boot project](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/config/PlaceholderConfigurerSupport.html), and its syntax has the following form:
`substitutableStartsWith` `EV` `Delimiter` `fallbackDefaultValue` `substitutableEndsWith` (for instance: `${Var1:Val1}`)

For instance, when the user supplies the following configurations:
- Foo = {Bar1:John}{Bar2}{Bar1:John}{Bar3:-Doe}
- Bar1 = Barista
- Bar2 = -Jean-

```c#
...buider.EnableSubstitutionsWithDelimitedFallbackDefaults("{", "}", ":");

var substituted = configuration["Foo"];
```

The `substituted` would return `Barista-Jean-Barista-Doe`. Notice that in this example, the fallback default value of `Bar1` doesn't override the EV initial value (i.e., `Barista`). Also, since `Bar3` doesn't have an EV declared; thus, it'd default back to the `-Doe` value instead.

If you like the idea and if it's ok to submit a PR, I have one ready with the feature fully implemented with various unit tests added to the project.

**Comment by molinch** [comment]
Hi @a-alamoudi  that sounds like a neat feature to have in 👍 
if you manage to keep it backwards compatible so that we can enable substitutions without support for defaults, then I'm all in

**Comment by molinch** [comment]
Thanks for the PR! merged

**Comment by molinch** [comment]
@a-alamoudi FYI nuget package pushed! It is 1.4.0

**Comment by a-alamoudi** [comment]
Hi @molinch,
Thank you for your earlier review and help. I revisited the test cases, and I believe there's a bug in how `EnableSubstitutionsWithDelimitedFallbackDefaults` treats two special cases. I found a discrepancy in handling non-resolvable variables and `null` substituted values different from the `EnableSubstitutions` method. Here's an example for each case:

- Non-resolvable:
   ```
   "TestKey" = "Test value {Foobar}"
   ```
- Substituted value is `null`:
   ```
   "Foo" = "{Var1}"
   "Var1" = null
   ```

In both cases, the `EnableSubstitutions` method throws an `UndefinedConfigVariableException`, given that the `exceptionOnMissingVariables` flag is set to `true` [^1]. When the `exceptionOnMissingVariables` flag is `false`, the method simply returns an empty string `""` [^2].

However, that's not the case for `EnableSubstitutionsWithDelimitedFallbackDefaults`. I noticed that when the user passes the correct starting and ending marks (e.g., `{` and `}` respectively), but with the wrong non-empty delimiter that doesn't match[^3], then the function returns the captured value as-is and ignores the `exceptionOnMissingVariables` flag altogether. That's wrong, and it should produce the same output as that of `EnableSubstitutions`. 

I applied the fixes to the code, and I'll be committing them to the same branch along with a couple of test cases added or expanded to reflect and ensure the correct behaviour. 

I'd appreciate it if you could take another look, and I apologize for any inconvenience this may cause.

Thanks!

[^1]:  For more details, please refer to tests: `Should_throw_for_non_resolved_variable` and `Should_throw_exception_when_substituted_value_is_null`.
[^2]:  For more details, please refer to test: `Should_ignore_non_resolved_variable`.
[^3]: Test `Should_throw_exception_when_fallback_default_value_delimiter_is_empty_without_substitutable_variable` correctly shows that an `UndefinedConfigVariableException` is thrown when an empty delimiter is passed.
