### ISSUE TITLE
Incorrect License Metadata in Nuspec File

### ISSUE THREAD

**Issue by regnrat** [molinch/ConfigurationSubstitutor#16]
I've noticed that the nuspec file has incorrect metadata for the license and licenseUrl properties. Specifically, the license property is set to `LICENSE`, but the correct license for this package is `MIT`. Additionally, the licenseUrl property is set to `https://aka.ms/deprecateLicenseUrl`, but the correct URL for this license is eg. `https://licenses.nuget.org/MIT`.

This issue is causing problems for me because I want to set up an automatic license check in my project. 
I would appreciate it if the package maintainer could update the nuspec file to reflect the correct license and URL.

Expected result:
The nuspec file should have correct metadata for the license and licenseUrl properties.

Actual result:
The nuspec file has incorrect metadata for the license and licenseUrl properties.

**Comment by molinch** [comment]
Thanks @regnrat for spotting this!
Would you have time for a small PR? Otherwise it will wait for a couple of days until I fix it

**Comment by regnrat** [comment]
Sure @molinch, i opened a PR - but I was not able to get that working without replacing the PackageLicenseFile with PackageLicenseExpression

**Comment by molinch** [comment]
Thanks a lot @regnrat it's 👍
In fact it should have been PackageLicenceExpression from the start, as per https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/nuget

**Comment by molinch** [comment]
Package 1.5.1 is pushed despite the CI error due to underlying issue https://github.com/brandedoutcast/publish-nuget/issues/76
