### ISSUE TITLE
how to substitute the variable from different file

### ISSUE THREAD

**Issue by AakritiLahoti** [molinch/ConfigurationSubstitutor#18]
if i have this variable in the appsettings file 
 "AuthenticationType": "${MiddlewareConfig_DefaultServiceAuthentication_AuthenticationType}",
 
 and i want to read the value of **MiddlewareConfig_DefaultServiceAuthentication_AuthenticationType** from a different file, is it possible ?

**Comment by molinch** [comment]
Yes it's possible but it has nothing to do with this library. You need to have a configuration source that points to this file, then it'll just work.
