### ISSUE TITLE
Add option to throw an exception for missing variable

### ISSUE THREAD

**Issue by erizzo** [molinch/ConfigurationSubstitutor#2]
If a variable name is referenced but isn't defined as a config key anywhere, the substitutor just silently uses the variable name 
as-is. It would be nice to have the option to make it throw an exception for any variable names that can't be resolved.

**Comment by erizzo** [comment]
Created PR #3 for it.

**Comment by molinch** [comment]
Thanks a lot @erizzo  it looks great, I'll test it then merge it and try to upload a nuget this evening!

**Comment by erizzo** [comment]
Do you think it should be the default behavior? I wanted to make it so but wasn't sure if you'd agree.

**Comment by molinch** [comment]
I agree it makes sense to be the default, and only opt-out if you need

**Comment by erizzo** [comment]
I'll update the PR to behave that way.

**Comment by erizzo** [comment]
PR is updated.

**Comment by molinch** [comment]
Nuget package published https://www.nuget.org/packages/ConfigurationSubstitutor/1.1.0
