### ISSUE TITLE
PR to allow nested substitution

### ISSUE THREAD

**Issue by bencyoung-Fignum** [molinch/ConfigurationSubstitutor#7]
Hi,

Do you accept PRs? I have one that allows nested substitution and detects recursive substitution

**Comment by bencyoung-Fignum** [comment]
Thanks for the excellent project BTW!

**Comment by molinch** [comment]
Hi @bencyoung-Fignum, Thanks a lot !
I would be more than happy if you submitted a PR. Please create unit tests for it then.
