### ISSUE TITLE
Net6 support

### ISSUE THREAD

**Issue by alvpickmans** [molinch/ConfigurationSubstitutor#9]
First of all, great project!

We are updating our APIs to .Net 6 and some of them use **ConfigurationSubstitutor**. We found a breaking change due to the fact in .Net 6 it was introduced this new [ConfigurationManager](https://github.com/dotnet/runtime/pull/55338) class. As this implements both `IConfigurationBuilder` and `IConfigurationRoot`, when calling `builder.Build()` it returns itself, resulting in any access to the `IConfigurationRoot` from the `ChainedSubstitutedConfigurationProvider` to end up on an infinite loop, as `ConfigurationManager` will end up iterating through all providers (this one included).

I found this article quite useful to understand the implications https://andrewlock.net/exploring-dotnet-6-part-1-looking-inside-configurationmanager-in-dotnet-6/#wait-what-s-configurationmanager-

I have a PR ready, hoping it is ok to submit it.

**Comment by molinch** [comment]
Hey Alvaro thanks for the detailed feedback on the issue.
It's really neat and interesting what they did, and will help me for a project we have where I worked!
If you have a PR feel free to submit it, happy to merge that in once reviewed.

**Comment by Jimm119** [comment]
Waiting on that to complete our Net 6 migration too =)

**Comment by molinch** [comment]
New nuget package is on nuget.org, thanks again @alvpickmans 👍 💯 🥇 
It's awesome learning new stuff via PR
